version: "3.9"

services:
  database:
    image: postgres
    container_name: database_ifoscar
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ifoscar
      - POSTGRES_DB=ifoscar
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
